# Generated by Django 4.2.5 on 2023-09-24 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("image_api", "0002_image_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="thumbnail",
            name="expiring_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="thumbnail",
            name="thumbnail",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="thumbnails/"
            ),
            preserve_default=False,
        ),
    ]
