# Generated by Django 4.2.5 on 2023-09-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_api", "0003_thumbnail_expiring_link_thumbnail_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="original_image_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="thumbnail",
            name="link_expires_in_seconds",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
