# Generated by Django 4.2.5 on 2023-09-25 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("image_api", "0004_image_original_image_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thumbnail",
            name="tier",
        ),
    ]
