on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - "5432:5432"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: psycopg2 prerequisites
        run: sudo apt update && sudo apt-get install libpq-dev

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Setup pipenv
        run: |
          python -m pip install --upgrade pipenv
      - name: Install pipenv packages
        run: |
          cd ./src
          pipenv install --dev

      - name: Create .env file
        run:
          cp .env.github .env

      - name: Run django test suite
        working-directory: ./src
        run: pipenv run python manage.py test

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
            python-version: '3.11'
      - name: Setup pipenv
        run: |
          python -m pip install --upgrade pipenv
      - name: Install pipenv packages
        run: |
          cd ./src
          pipenv install --dev

      - name: Create .env file
        run:
          cp .env.example .env

      - name: Run django check suite dev
        working-directory: ./src
        run: pipenv run python manage.py check --fail-level ERROR

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Setup pipenv
        run: |
          python -m pip install --upgrade pipenv
      - name: Install pipenv packages
        run: |
          cd ./src
          pipenv install --dev
      - name: Run linter
        run: |
          cd ./src
          pipenv run prospector
